### PR TITLE
use dc:title for naming address books as de-facto done in SolidOS.

### PR DESCRIPTION
**Pull request by angelo-v**
ref: https://github.com/solid/contacts/issues/1

### CODE REVIEW

**Review by timbl — APPROVED** [review]
L g t m. Separate issue may be moving all Dc to DcT

**Comment by angelo-v** [comment]
Oh no, my mistake, SolidOS is using DC terms, just with the prefix dc. I will adjust the MR

**Comment by angelo-v** [comment]
@timbl Is this ready to be merged then? (I have no merge permission myself)

**Comment by timbl** [comment]
Following meeting

**Pull request merged**
